"""
Trình tạo và quản lý toàn bộ dữ liệu 87 lệnh Dashboard đa ngôn ngữ (6 thứ tiếng).
Hỗ trợ: Tiếng Việt (vi), English (en), 中文 (zh), Español (es), Português (pt), Français (fr).
"""
import copy

# Dictionary of translations for common preview / argument tokens
_I18N_TERMS = {
    "vi": {
        "cat_overview": "Tổng quan",
        "cat_info": "Thông tin",
        "cat_music": "Âm nhạc",
        "cat_moderation": "Điều hành",
        "cat_fun": "Vui vẻ & Tình cảm",
        "cat_birthday": "Sinh nhật",
        "cat_economy": "Kinh tế & Shop",
        "cat_tempvoice": "Voice Tạm thời",
        "cat_customcmd": "Lệnh Tùy biến",
        "cat_ai": "Trợ lý AI",
        "cat_tickets": "Hỗ trợ Tickets",
        "cat_automod": "Kiểm duyệt tự động",
        "cat_autoroles": "Tự động cấp Role",
        "cat_reactionroles": "Reaction Roles",
        "cat_leveling": "Cấp bậc & XP",
        "cat_giveaways": "Phát quà Giveaway",
    },
    "en": {
        "cat_overview": "Overview",
        "cat_info": "Information",
        "cat_music": "Music",
        "cat_moderation": "Moderation",
        "cat_fun": "Fun & Social",
        "cat_birthday": "Birthday",
        "cat_economy": "Economy & Shop",
        "cat_tempvoice": "Temp Voice Hub",
        "cat_customcmd": "Custom Commands",
        "cat_ai": "AI Assistant",
        "cat_tickets": "Support Tickets",
        "cat_automod": "AutoMod",
        "cat_autoroles": "Auto Roles",
        "cat_reactionroles": "Reaction Roles",
        "cat_leveling": "Leveling & XP",
        "cat_giveaways": "Giveaways",
    },
    "zh": {
        "cat_overview": "概览",
        "cat_info": "信息",
        "cat_music": "音乐 🎵",
        "cat_moderation": "管理",
        "cat_fun": "趣味与社交",
        "cat_birthday": "生日",
        "cat_economy": "经济与商店",
        "cat_tempvoice": "动态语音房",
        "cat_customcmd": "自定义指令",
        "cat_ai": "AI 智能助手",
        "cat_tickets": "客服工单",
        "cat_automod": "自动审核",
        "cat_autoroles": "自动身份组",
        "cat_reactionroles": "反应身份组",
        "cat_leveling": "等级与经验",
        "cat_giveaways": "抽奖活动",
    },
    "es": {
        "cat_overview": "General",
        "cat_info": "Información",
        "cat_music": "Música",
        "cat_moderation": "Moderación",
        "cat_fun": "Diversión y Social",
        "cat_birthday": "Cumpleaños",
        "cat_economy": "Economía y Tienda",
        "cat_tempvoice": "Voz Temporal",
        "cat_customcmd": "Comandos Personalizados",
        "cat_ai": "Asistente AI",
        "cat_tickets": "Tickets de Soporte",
        "cat_automod": "AutoMod",
        "cat_autoroles": "Auto Roles",
        "cat_reactionroles": "Roles de Reacción",
        "cat_leveling": "Niveles y XP",
        "cat_giveaways": "Sorteos",
    },
    "pt": {
        "cat_overview": "Geral",
        "cat_info": "Informações",
        "cat_music": "Música",
        "cat_moderation": "Moderação",
        "cat_fun": "Diversão e Social",
        "cat_birthday": "Aniversários",
        "cat_economy": "Economia e Loja",
        "cat_tempvoice": "Voz Temporária",
        "cat_customcmd": "Comandos Personalizados",
        "cat_ai": "Assistente AI",
        "cat_tickets": "Tickets de Suporte",
        "cat_automod": "AutoMod",
        "cat_autoroles": "Auto Cargos",
        "cat_reactionroles": "Cargos por Reação",
        "cat_leveling": "Níveis e XP",
        "cat_giveaways": "Sorteios",
    },
    "fr": {
        "cat_overview": "Général",
        "cat_info": "Informations",
        "cat_music": "Musique",
        "cat_moderation": "Modération",
        "cat_fun": "Divertissement & Social",
        "cat_birthday": "Anniversaire",
        "cat_economy": "Économie & Boutique",
        "cat_tempvoice": "Salons Temporaires",
        "cat_customcmd": "Commandes Personnalisées",
        "cat_ai": "Assistant IA",
        "cat_tickets": "Tickets de Support",
        "cat_automod": "Modération Auto",
        "cat_autoroles": "Rôles Automatiques",
        "cat_reactionroles": "Rôles par Réaction",
        "cat_leveling": "Niveaux & XP",
        "cat_giveaways": "Concours Giveaways",
    }
}
