"""
database — Package truy cập SQLite của ZerynBot V2 (tách từ database.py, Giai đoạn 3.3).

Cách dùng KHÔNG đổi so với trước:
    from database import async_get_guild_settings, get_guild_settings
    database.set_db_path(path)    # API DUY NHẤT để trỏ DB (test/CLI)

Nội bộ:
    conn.py         DB_PATH + PRAGMA + _connect_sync/_connect_async (duy nhất)
    schema.py       init_db() — tạo bảng/index
    guilds.py       settings guild, module, cache kênh/role, blacklist, global setting
    embeds.py       embed đã lưu (dashboard)
    tickets.py      panel ticket & reaction roles
    music.py        playlist, cache bài hát, top played
    community.py    logger, automod, verify, moderation, custom commands
    leveling.py     leveling/XP
    economy.py      kinh tế & shop
    events.py       giveaway, nhắc hẹn, fun/marriage, sinh nhật, voice tạm
    ai.py           cấu hình AI + log hoạt động AI
    activity.py     activity log, sự kiện, support threads
    maintenance.py  prune, WAL checkpoint, VACUUM
"""
import sys

from . import conn
from .conn import (
    BASE_DIR,
    DB_BUSY_TIMEOUT_MS,
    DB_CACHE_SIZE_KB,
    DB_MMAP_BYTES,
    VACUUM_FREELIST_THRESHOLD,
    _connect_async,
    _connect_sync,
    _row_to_dict,
    get_db_connection,
    get_db_path,
    set_db_path,
)
from .schema import init_db

from .guilds import (
    get_guild_settings,
    upsert_guild,
    get_guild_modules,
    set_module,
    get_guild_channels,
    get_guild_categories,
    get_guild_voice_channels,
    get_guild_roles,
    get_guild_meta,
    get_bot_guild_ids,
    get_top_users,
    async_get_guild_settings,
    async_increment_stat,
    get_guild_stats,
    async_is_module_enabled,
    async_get_guild_modules,
    async_cache_guild,
    async_remove_guild,
    async_cache_channels,
    async_cache_roles,
    set_guild_language,
    async_set_guild_language,
    get_global_setting,
    set_global_setting,
    async_get_global_setting,
    get_blacklist,
    add_to_blacklist,
    remove_from_blacklist,
    is_blacklisted,
    async_is_blacklisted,
    async_add_to_blacklist,
    DEFAULT_MODULES,
    _DEFAULT_SETTINGS,
    set_module_enabled,
)

from .embeds import (
    get_saved_embeds,
    save_embed,
    delete_embed,
    async_get_saved_embeds,
    async_get_saved_embed_by_name,
)

from .tickets import (
    get_ticket_panels,
    get_ticket_panel,
    save_ticket_panel,
    delete_ticket_panel,
    update_panel_message_id,
    get_reaction_roles_panels,
    get_reaction_roles_panel,
    save_reaction_roles_panel,
    delete_reaction_roles_panel,
    update_reaction_roles_message_id,
    async_get_all_ticket_panels,
    async_get_ticket_button,
    async_get_reaction_role_item,
)

from .music import (
    get_playlists,
    get_playlist,
    get_playlist_by_name,
    create_playlist,
    delete_playlist,
    add_track_to_playlist,
    delete_track_from_playlist,
    get_playlist_of_track,
    get_playlist_tracks,
    async_get_playlists,
    async_get_playlist_by_name,
    async_get_song_cache,
    async_set_song_cache,
    async_delete_song_cache,
    async_create_playlist,
    async_delete_playlist,
    async_add_track_to_playlist,
    async_delete_track_from_playlist,
    async_get_playlist_tracks,
    async_get_top_played_songs,
    get_top_played_songs,
)

from .community import (
    get_logger_settings,
    set_logger_settings,
    async_get_logger_settings,
    get_automod_settings,
    upsert_automod_settings,
    async_get_automod_settings,
    async_update_automod_settings,
    async_add_automod_warning,
    async_clear_automod_warnings,
    get_verify_settings,
    upsert_verify_settings,
    async_get_verify_settings,
    async_upsert_verify_settings,
    async_add_mod_warning,
    async_get_mod_warnings,
    async_count_mod_warnings,
    async_delete_mod_warning,
    get_mod_warnings_count_sync,
    get_custom_commands,
    get_custom_command,
    add_custom_command,
    update_custom_command,
    delete_custom_command,
    _custom_cmds_cache_key,
    invalidate_custom_commands_cache,
    async_get_custom_commands,
    async_find_custom_command,
    async_add_custom_command,
    async_delete_custom_command,
    async_increment_custom_command_usage,
    async_count_user_custom_commands,
    async_count_guild_custom_commands,
    _DEFAULT_AUTOMOD,
    _DEFAULT_VERIFY,
    _CUSTOM_CMDS_TTL,
)

from .leveling import (
    get_leveling_settings,
    set_leveling_settings,
    get_level_roles,
    set_level_roles,
    async_get_leveling_settings,
    async_get_level_roles,
    async_get_user_level,
    async_update_user_xp,
    async_reset_user_xp,
    async_get_top_users,
    async_get_user_rank,
    _DEFAULT_LEVELING,
    async_get_user_xp,
)

from .economy import (
    get_economy_settings,
    update_economy_settings,
    get_economy_shop,
    add_economy_shop_item,
    delete_economy_shop_item,
    get_top_economy_users,
    update_user_balance,
    async_get_economy_settings,
    async_get_economy_user,
    async_claim_daily,
    async_claim_economy_cooldown,
    async_modify_wallet,
    async_place_bet,
    async_log_transaction,
    async_get_user_transactions,
    async_transfer_money,
    async_get_economy_shop,
    async_deposit_money,
    async_withdraw_money,
    async_buy_shop_item,
    async_refund_shop_purchase,
    async_get_top_economy,
    async_get_inventory,
    async_get_inventory_item,
    async_add_inventory_item,
    async_sell_inventory_item,
    async_sell_all_inventory,
    async_get_economy_cooldown,
    async_set_economy_cooldown,
)

from .events import (
    async_create_giveaway,
    async_get_giveaway,
    async_update_giveaway,
    async_get_active_giveaways,
    async_add_reminder,
    async_get_due_reminders,
    async_delete_reminder,
    async_get_user_reminders,
    async_get_marriage,
    async_create_marriage,
    async_delete_marriage,
    async_add_love_points,
    get_marriages_count_sync,
    async_increment_fun_interaction,
    async_get_fun_interaction_count,
    async_set_birthday,
    async_get_birthday,
    async_remove_birthday,
    async_get_birthdays_today,
    async_get_upcoming_birthdays,
    async_get_birthday_settings,
    async_upsert_birthday_settings,
    get_birthday_settings_sync,
    upsert_birthday_settings_sync,
    get_birthdays_this_month_count,
    get_tempvoice_settings,
    update_tempvoice_settings,
    get_active_temp_channels,
    delete_tempvoice_channel,
    async_get_tempvoice_settings,
    async_add_active_temp_channel,
    async_remove_active_temp_channel,
    async_get_active_temp_channel,
    async_update_temp_channel_lock,
)

from .ai import (
    get_ai_settings,
    update_ai_settings,
    async_get_ai_settings,
    log_ai_activities_batch,
    log_ai_activity,
    async_log_ai_activity,
    get_ai_activity_snapshot,
    _last_known_models_stats,
    _models_stats_lock,
)

from .activity import (
    log_activity,
    async_log_activity,
    _format_activity_rows,
    get_recent_guild_events,
    async_get_recent_guild_events,
    get_system_activity_logs,
    async_get_system_activity_logs,
    get_or_create_support_thread,
    get_support_thread,
    get_support_messages,
    add_support_message,
    atomic_escalate_support_thread,
    get_all_support_threads,
    update_support_thread_status,
    mark_support_thread_read,
)

from .maintenance import (
    wal_checkpoint,
    async_wal_checkpoint,
    snapshot_database,
    async_get_maintenance_job,
    async_set_maintenance_job,
    async_prune_old_data,
    async_vacuum_db,
)


__all__ = [
    "BASE_DIR", "DB_PATH", "get_db_path", "set_db_path", "init_db",
    "get_db_connection", "_connect_sync", "_connect_async", "_row_to_dict",
    "DB_BUSY_TIMEOUT_MS", "DB_CACHE_SIZE_KB", "DB_MMAP_BYTES", "VACUUM_FREELIST_THRESHOLD",
    "get_guild_settings",
    "upsert_guild",
    "get_guild_modules",
    "set_module",
    "get_guild_channels",
    "get_guild_categories",
    "get_guild_voice_channels",
    "get_guild_roles",
    "get_guild_meta",
    "get_bot_guild_ids",
    "get_top_users",
    "async_get_guild_settings",
    "async_increment_stat",
    "get_guild_stats",
    "async_is_module_enabled",
    "async_get_guild_modules",
    "async_cache_guild",
    "async_remove_guild",
    "async_cache_channels",
    "async_cache_roles",
    "set_guild_language",
    "async_set_guild_language",
    "get_global_setting",
    "set_global_setting",
    "async_get_global_setting",
    "get_blacklist",
    "add_to_blacklist",
    "remove_from_blacklist",
    "is_blacklisted",
    "async_is_blacklisted",
    "async_add_to_blacklist",
    "get_saved_embeds",
    "save_embed",
    "delete_embed",
    "async_get_saved_embeds",
    "async_get_saved_embed_by_name",
    "get_ticket_panels",
    "get_ticket_panel",
    "save_ticket_panel",
    "delete_ticket_panel",
    "update_panel_message_id",
    "get_reaction_roles_panels",
    "get_reaction_roles_panel",
    "save_reaction_roles_panel",
    "delete_reaction_roles_panel",
    "update_reaction_roles_message_id",
    "async_get_all_ticket_panels",
    "async_get_ticket_button",
    "async_get_reaction_role_item",
    "get_playlists",
    "get_playlist",
    "get_playlist_by_name",
    "create_playlist",
    "delete_playlist",
    "add_track_to_playlist",
    "delete_track_from_playlist",
    "get_playlist_of_track",
    "get_playlist_tracks",
    "async_get_playlists",
    "async_get_playlist_by_name",
    "async_get_song_cache",
    "async_set_song_cache",
    "async_delete_song_cache",
    "async_create_playlist",
    "async_delete_playlist",
    "async_add_track_to_playlist",
    "async_delete_track_from_playlist",
    "async_get_playlist_tracks",
    "async_get_top_played_songs",
    "get_top_played_songs",
    "get_logger_settings",
    "set_logger_settings",
    "async_get_logger_settings",
    "get_automod_settings",
    "upsert_automod_settings",
    "async_get_automod_settings",
    "async_update_automod_settings",
    "async_add_automod_warning",
    "async_clear_automod_warnings",
    "get_verify_settings",
    "upsert_verify_settings",
    "async_get_verify_settings",
    "async_upsert_verify_settings",
    "async_add_mod_warning",
    "async_get_mod_warnings",
    "async_count_mod_warnings",
    "async_delete_mod_warning",
    "get_mod_warnings_count_sync",
    "get_custom_commands",
    "get_custom_command",
    "add_custom_command",
    "update_custom_command",
    "delete_custom_command",
    "_custom_cmds_cache_key",
    "invalidate_custom_commands_cache",
    "async_get_custom_commands",
    "async_find_custom_command",
    "async_add_custom_command",
    "async_delete_custom_command",
    "async_increment_custom_command_usage",
    "async_count_user_custom_commands",
    "async_count_guild_custom_commands",
    "get_leveling_settings",
    "set_leveling_settings",
    "get_level_roles",
    "set_level_roles",
    "async_get_leveling_settings",
    "async_get_level_roles",
    "async_get_user_level",
    "async_update_user_xp",
    "async_reset_user_xp",
    "async_get_top_users",
    "async_get_user_rank",
    "get_economy_settings",
    "update_economy_settings",
    "get_economy_shop",
    "add_economy_shop_item",
    "delete_economy_shop_item",
    "get_top_economy_users",
    "update_user_balance",
    "async_get_economy_settings",
    "async_get_economy_user",
    "async_claim_daily",
    "async_claim_economy_cooldown",
    "async_modify_wallet",
    "async_place_bet",
    "async_log_transaction",
    "async_get_user_transactions",
    "async_transfer_money",
    "async_get_economy_shop",
    "async_deposit_money",
    "async_withdraw_money",
    "async_buy_shop_item",
    "async_refund_shop_purchase",
    "async_get_top_economy",
    "async_get_inventory",
    "async_get_inventory_item",
    "async_add_inventory_item",
    "async_sell_inventory_item",
    "async_sell_all_inventory",
    "async_get_economy_cooldown",
    "async_set_economy_cooldown",
    "async_create_giveaway",
    "async_get_giveaway",
    "async_update_giveaway",
    "async_get_active_giveaways",
    "async_add_reminder",
    "async_get_due_reminders",
    "async_delete_reminder",
    "async_get_user_reminders",
    "async_get_marriage",
    "async_create_marriage",
    "async_delete_marriage",
    "async_add_love_points",
    "get_marriages_count_sync",
    "async_increment_fun_interaction",
    "async_get_fun_interaction_count",
    "async_set_birthday",
    "async_get_birthday",
    "async_remove_birthday",
    "async_get_birthdays_today",
    "async_get_upcoming_birthdays",
    "async_get_birthday_settings",
    "async_upsert_birthday_settings",
    "get_birthday_settings_sync",
    "upsert_birthday_settings_sync",
    "get_birthdays_this_month_count",
    "get_tempvoice_settings",
    "update_tempvoice_settings",
    "get_active_temp_channels",
    "delete_tempvoice_channel",
    "async_get_tempvoice_settings",
    "async_add_active_temp_channel",
    "async_remove_active_temp_channel",
    "async_get_active_temp_channel",
    "async_update_temp_channel_lock",
    "get_ai_settings",
    "update_ai_settings",
    "async_get_ai_settings",
    "log_ai_activities_batch",
    "log_ai_activity",
    "async_log_ai_activity",
    "get_ai_activity_snapshot",
    "log_activity",
    "async_log_activity",
    "_format_activity_rows",
    "get_recent_guild_events",
    "async_get_recent_guild_events",
    "get_system_activity_logs",
    "async_get_system_activity_logs",
    "get_or_create_support_thread",
    "get_support_thread",
    "get_support_messages",
    "add_support_message",
    "atomic_escalate_support_thread",
    "get_all_support_threads",
    "update_support_thread_status",
    "mark_support_thread_read",
    "wal_checkpoint",
    "async_wal_checkpoint",
    "snapshot_database",
    "async_get_maintenance_job",
    "async_set_maintenance_job",
    "async_prune_old_data",
    "async_vacuum_db",
    "DEFAULT_MODULES",
    "_DEFAULT_SETTINGS",
    "_DEFAULT_AUTOMOD",
    "_DEFAULT_VERIFY",
    "_CUSTOM_CMDS_TTL",
    "_DEFAULT_LEVELING",
    "_last_known_models_stats",
    "_models_stats_lock",
    "set_module_enabled",
    "async_get_user_xp",
]


def __getattr__(name):
    """Tương thích ngược: `database.DB_PATH` luôn phản ánh giá trị hiện tại."""
    if name == "DB_PATH":
        return conn.DB_PATH
    raise AttributeError(f"module 'database' has no attribute {name!r}")


def __dir__():
    """Thêm DB_PATH vào dir() dù nó là thuộc tính động (test API surface dùng)."""
    return sorted(list(globals().keys()) + ["DB_PATH"])
